#!/bin/bash

BRAIN_DIR=~/brain
if [ -z $EDITOR ] ; then
	EDITOR=vim
fi

datetime=$(date +%Y-%m-%d\ %H:%M:%S)
date=$(echo $datetime | awk '{print $1}')
time=$(echo $datetime | awk '{print $2}')

if [ ! -d $BRAIN_DIR/$date ] ; then
	mkdir -p $BRAIN_DIR/$date
fi

tmpfile=$(mktemp /tmp/brain.XXXXXX)

if [ -t 0 ] ; then
	if [[ "$@" != "" ]] ; then
		echo "$@" >> $tmpfile
	fi
else
	while read -r line ; do
		echo $line >> $tmpfile
	done
fi

eval "$EDITOR $tmpfile"

count=$(wc -c $tmpfile | awk '{print $1}')

if [ $count -ne 0 ] ; then
	filename="$BRAIN_DIR/$date/$time"
	keywords=$(head -n1 $tmpfile | tr -Cd 'A-Za-z0-9 _-' | tr 'A-Z' 'a-z' | sed 's/ /_/g')
	if [[ "$keywords" != "" ]] ; then
		filename="${filename}.${keywords}"
	fi
	cat $tmpfile > $filename
fi

rm $tmpfile
