#!/bin/bash

BRAIN_DIR=~/brain

usage() {
  cat << EOF 1>&2
Usage: $0 [ -t TIME ] [ PATTERN ]
   -t TIME	Specify a time to search back to (1h, 1d, 7d) defaults to '1d'
EOF
exit 1
}

TIME=""
while getopts 'ht:' c
do
  case $c in
    h) usage ;;
    t) TIME=$OPTARG ;;
  esac
done

# Remove the parameters
shift $((OPTIND-1))

if [[ "$TIME" == "" ]] ; then
	TIME=1d
fi

command="find $BRAIN_DIR -type f -mtime -$TIME"

regex="^#"
for w in $@ ; do
	if [[ $w =~ $regex ]] ; then
		w="${w:1}"
	fi
	command="$command | egrep '$w'"
done

for f in $(eval "$command") ; do
	header=$(echo "$f" | sed "s#${BRAIN_DIR}/##g" | sed "s#\..*##")
	echo -n "$header "
	head -n1 $f
done
